### ISSUE TITLE
IOException in Apex Launcher download

### ISSUE THREAD

**Issue by ApexPlayer681** [baph-omet/Apex-Launcher#50]
# Exception Details
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at ApexLauncher.DownloadForm.StreamFile(HttpWebResponse fileresp, IDownloadable download)
   at ApexLauncher.DownloadForm.Download()

# Configuration
* Current Launcher Version: 1.7.2.0
* Current Game Version: 
* Install Path: C:\Users\Jhay\Downloads

# Files
* `config.txt`
* C:\Users\Jhay\Downloads:
    * C:\Users\Jhay\Downloads\Versions:
        * C:\Users\Jhay\Downloads\Versions\ALPHA 9
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`
    * C:\Users\Jhay\Downloads\Versions:
        * C:\Users\Jhay\Downloads\Versions\ALPHA 9.2p
        * C:\Users\Jhay\Downloads\Versions\ALPHA 9.2p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`
    * C:\Users\Jhay\Downloads\Versions:
    * C:\Users\Jhay\Downloads\Versions:
        * C:\Users\Jhay\Downloads\Versions\Audio v1

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0
* .NET Runtime Version: 4.0.30319.42000

**Comment by ApexPlayer681** [comment]
> Seems like a network disconnect while downloading the audio package. Does this happen every time?

Yep, every time. Every time i start download, the bar stops at a random number like 1/3 45% or 2/3 57%. The bar stops for like 3 to 5 minutes and an error catcher window appears.
